### ISSUE TITLE
thêm cái password ở đây.

### ISSUE THREAD

**Issue by dh6k** [KhanhNguyen9872/PublicFile#2]
https://www.youtube.com/channel/UC1Npa_Mu85Qo1Rut5K1Rh7g
Cái này là password cho những ai muốn tải file mà nó yêu cầu nhập password

**Comment by KhanhNguyen9872** [comment]
> https://www.youtube.com/channel/UC1Npa_Mu85Qo1Rut5K1Rh7g Cái này là password cho những ai muốn tải file mà nó yêu cầu nhập password

thanks
